# -*- coding: utf-8 -*-
"""Ch8_개미전사

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3xoCalNUSsL4B6xmAYu_QYrIfpY1Xv8
"""

#개미전사

n = int(input())
arr = list(map(int, input().split()))

d = [0] * 100

d[0] = arr[0]
d[1] = max(arr[0], arr[1])
for i in range(2, n):
  d[i] = max(arr[i-1], arr[i-2] + arr[i])

print(d[n-1])

