# -*- coding: utf-8 -*-
"""Ch8_바닥공사

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13NL4N24MMvNh_mZm83hipGisLyjvyNk5
"""

#바닥공사

n =int(input())

d = [0] * 100

d[1] = 1
d[2] = 3

for i in range(3, n+1):
  d[i] = (d[i-1] + 2 * d[i-2]) % 796796

print(d[n])

5