--SET1: 고양이와 개는 몇 마리 있을까

SELECT ANIMAL_TYPE, COUNT(ANIMAL_ID) AS 'count'
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;

--SET2: 동명 동물 수 찾기
--데이터 출력 뿐만 아니라 집계 과정에서의 필터링도 주의

SELECT NAME, COUNT(*) AS COUNT
FROM ANIMAL_INS
WHERE NAME <> ''
GROUP BY NAME
HAVING COUNT >= 2
ORDER BY NAME;

--SET3: 입양 시각 구하기(1)

SELECT HOUR(DATETIME), COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
HAVING COUNT >= 2
ORDER BY NAME;

--SET4: 입양 시각 구하기(2)

WITH RECURSIVE ADD_HOURS AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM ADD_HOURS
    WHERE HOUR < 23
)

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ADD_HOURS
LEFT JOIN ANIMAL_OUTS 
ON HOUR = HOUR(DATETIME)
GROUP BY HOUR;

