# -*- coding: utf-8 -*-
"""Ch8_1로만들기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Oge_4rAeP2WDMqUJSyu_K2GwN74JBNH
"""

#1로 만들기 (재풀이)

X = int(input())
arr = [0] * 100

for i in range(2, X+1):
    arr[i] = arr[i-1] + 1

    if i % 2 == 0:
        arr[i] = min(arr[i], arr[i // 2] + 1)

    if i % 3 == 0:
        arr[i] = min(arr[i], arr[i // 3] + 1)

    if i % 5 == 0:
        arr[i] = min(arr[i], arr[i // 5] + 1)

print(arr)

#1로 만들기 (정답)

X = int(input())
arr = [0] * 100

for i in range(2, X+1):
  arr[i] = arr[i-1] + 1
  if i % 2 == 0:
    arr[i] = min(arr[i], arr[i // 2] + 1)
  if i % 3 == 0:
    arr[i] = min(arr[i], arr[i // 3] + 1)
  if i % 5 == 0:
    arr[i] = min(arr[i], arr[i // 5] + 1)

print(arr[i])
    

#1로 만들기 (틀린 풀이)

X = int(input())

arr = [0] * 100
count = 0

def makeone(x):
  global count
  if arr[count] == 1:
    return count
  
  if x % 5 == 0:
    count += 1
    arr[count] = x // 5
    return makeone(arr[count])

  elif x % 3 == 0:
    count += 1
    arr[count] = x // 3
    return makeone(arr[count])

  elif x % 2 == 0:
    count +=1
    arr[count] = x // 2
    return makeone(arr[count])

  else: 
    arr[count] = x - 1
    return makeone(arr[count])

  print(count)

print(makeone(X))
print(arr)

22
