# -*- coding: utf-8 -*-
"""Chapter8_DP_Concepts.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gv0EJ09Vye_EzuOfxWIDoDN3YUp6fG0l
"""



#210202_DP_Concepts

#Pibonacci Recursive

def pibo(x):
  if x == 1 or x == 2:
    return 1
  return pibo(x-1) + pibo(x-2)

print(pibo(4))


#Pibonacci DP(TopDown)

arr = [0] * 100

def piboDP(x):
  if x == 1 or x == 2:
    return 1
  if arr[x] != 0:
    return arr[x]
  arr[x] = piboDP(x-1) + piboDP(x-2)
  return arr[x]

piboDP(4)

#Pibonacci DP(BottomUp)

arr = [0] * 100

arr[1] = 1
arr[2] = 1
n = 4

for i in range(3, n+1):
  arr[i] = arr[i-1] + arr[i-2]

print(arr[n])

